### ISSUE TITLE
draw function and redo, undo method

### ISSUE THREAD

**Issue by GuenKainto** [rkishan516/whiteboard#2]
Hello, thank you for this library. I have a question about the drawing feature of the library.
I created a simple Note program with Flutter. When I draw with 1 finger it works fine without any problem, but if I use 2 fingers it connects the 2 points into a straight line as shown in the picture. And I tried using it with eraser too, it works the same. Is this a bug or is it a feature? I tested it on Keep note software on Android and it seems like it's not like that.

![image](https://github.com/rkishan516/whiteboard/assets/109414890/15a0fe1a-5d5b-49f1-9286-d2d83a8585b6)

And by the way, I'm also having difficulty using the redo and undo buttons. Can you give me instructions or a demo code, I can't find it.
Thank you so much !

**Comment by rkishan516** [comment]
Hey @GuenKainto, We don't have support for multi touch yet.

On the other hand, about redo and undo it's already there in documentation but here we go
* I am assuming you have `whiteboardController`
* For undo, call  `whiteboardController.undo()`
* For redo, call  `whiteboardController.redo()`

**Comment by GuenKainto** [comment]
Oh wow,Thank you. I don't think just calling the function like this will solve the problem 
When I saw the onRedoUndo part in the documentation, I thought I needed to do something with it.
WhiteBoard(
    // background Color of white board
    backgroundColor: Colors.white,
    // Controller for action on whiteboard
    controller: WhiteBoardController(),
    // Stroke width of freehand
    strokeWidth: 5,
    // Stroke color of freehand
    strokeColor: Colors.green,
    // For Eraser mode
    isErasing: false,
    // Save image
    onConvertImage: (list){},
    // Callback common for redo or undo
    onRedoUndo: (t,m){},
)
Once again, thank you

**Comment by rkishan516** [comment]
Yaa, `onRedoUndo` is callback which called once `undo` or `redo` is done.

**Comment by GuenKainto** [comment]
Hello, do you mind if I have a question about customize the location to save the file? It seems that with the whiteBoardController.convertToImage() function it automatically points to the phone's download folder.

onConvertImage: (Uint8List imageList) async{

  final DateFormat dateFormat = DateFormat('dd/MM/yyyy-hh:mm:ss');
  final dir = await getTemporaryDirectory();
  //final filePath = '${dir.path}/${DateTime.now()}_result_image.png';

  await FileSaver.instance.saveAs(
      name: '${dateFormat.format(DateTime.now())}_result_image',
      ext: 'png',
      mimeType: MimeType.png,
      bytes: imageList,
      filePath: dir.path);

},

The code i call the function: 

IconButton(
  onPressed: () {
    whiteBoardController.convertToImage();
  },
  icon: const Icon(
    Icons.save_alt,
  ),
),
    
I want to save the image file to the cache folder (without choosing a location to save the file) and then Navigate.pop returns the file location. Is that possible?

Thank you.

**Comment by rkishan516** [comment]
Hey @GuenKainto, whiteboard by default just gives you image.
Whatever you want to do with that image is upto you, wherever you want to save, you can.
It'll not restrict you.

**Comment by GuenKainto** [comment]
Thank you for your answer, so it must be because I am not using FileSaver correctly.
